services:
  db:
    image: registry.lil.tools/library/postgres:16.6
    volumes:
      - db_data_16:/var/lib/postgresql/data:delegated
    ports:
      - "127.0.0.1:54320:5432"
    environment:
      - POSTGRES_PASSWORD=example

  web:
    image: registry.lil.tools/harvardlil/h2o-python:0.116-e8e0e89b52809177c75b1876c3cba8da
    tty: true
    command: bash
    environment:
    - DOCKERIZED=true
    - PDF_EXPORT_BUCKET=h2o.pdf_exports

    volumes:
      - .:/app:delegated
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8080:8080"
    extra_hosts:
      - "opencasebook.test:127.0.0.1"
    networks:
      default:
        aliases:
          - 'opencasebook.test'
    depends_on:
      - db
    # allow profiling with py-spy
    # https://github.com/benfred/py-spy#how-do-i-run-py-spy-in-docker
    cap_add:
        - SYS_PTRACE

  minio:
    image: registry.lil.tools/minio/minio:RELEASE.2021-02-19T04-38-02Z
    entrypoint:
      - "/entrypoint.sh"
    command:
      - "server"
      - "/data"
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
      - DATA_DIR=/data
      - BUCKET=h2o.images
      - EXPORT_BUCKET=h2o.exports
      - PDF_EXPORT_BUCKET=h2o.pdf_exports
    volumes:
      - ./docker/minio/entrypoint.sh:/entrypoint.sh
      - minio_data:/data:delegated
    ports:
      - "127.0.0.1:9000:9000"
    extra_hosts:
      - "opencasebook.minio.test:127.0.0.1"
    networks:
      default:
        aliases:
          - 'opencasebook.minio.test'

  pandoc-lambda:
    image: registry.lil.tools/harvardlil/h2o-pandoc-lambda:0.66-f4ef497565cd325e6161cb6b0dafe814
    tty: true
    environment:
      - USE_S3_CREDENTIALS=True
      - AWS_ACCESS_KEY_ID=accesskey
      - AWS_SECRET_ACCESS_KEY=secretkey
      - S3_ENDPOINT_URL=http://minio:9000
      - EXPORT_BUCKET=h2o.exports
    # volumes: is set for local dev in docker-compose.override.yml
    # Uncomment to disable entrypoint if changes to requirements mean container can't start:
    # command: bash

volumes:
  db_data_12:
  db_data_16:
  minio_data:

networks:
  default:
