# Generated by Django 3.2.25 on 2024-05-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_add_courtlistener_api_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='ali_licensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcontentnode',
            name='ali_licensed',
            field=models.BooleanField(default=False),
        )
    ]