# Generated by Django 3.2.25 on 2024-05-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20240516_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcasebook',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical casebook', 'verbose_name_plural': 'historical casebooks'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontentannotation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical content annotation', 'verbose_name_plural': 'historical content annotations'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontentnode',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical content node', 'verbose_name_plural': 'historical content nodes'},
        ),
        migrations.AlterModelOptions(
            name='historicallegaldocument',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical legal document', 'verbose_name_plural': 'historical legal documents'},
        ),
        migrations.AlterModelOptions(
            name='historicallink',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical link', 'verbose_name_plural': 'historical links'},
        ),
        migrations.AlterModelOptions(
            name='historicaltextblock',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical text block', 'verbose_name_plural': 'historical text blocks'},
        ),
        migrations.AlterField(
            model_name='historicalcasebook',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcontentannotation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcontentnode',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallegaldocument',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallink',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltextblock',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
